namespace Magpie.Runtime
{
    [default_interface]
    runtimeclass MagRuntime 
    {
        MagRuntime();

        void Run(UInt64 hwndSrc, MagSettings settings);
        void Stop();

        Boolean IsRunning { get; };
    }
}
