namespace Magpie.Runtime
{
    [default_interface]
    runtimeclass MagRuntime 
    {
        MagRuntime();

        Boolean Scale(UInt64 hwndSrc, MagSettings settings);

        Boolean IsRunning { get; };
    }
}
