namespace Magpie.Runtime
{
	enum CaptureMode {
		GraphicsCapture,
		DesktopDuplication,
		GDI,
		DwmSharedSurface
	};

	enum MultiMonitorUsage {
		Nearest,
		Intersected,
		All
	};

	struct Cropping {
		Double Left;
		Double Top;
		Double Right;
		Double Bottom;
	};

	[default_interface]
	runtimeclass MagSettings
	{
		MagSettings();

		void CopyFrom(MagSettings other);

		CaptureMode CaptureMode;
		MultiMonitorUsage MultiMonitorUsage;
		// 0 为默认，否则应减一得到枚举序号
		UInt32 GraphicsAdapter;
		Boolean IsDisableWindowResizing;
		Boolean IsReserveTitleBar;
		Cropping Cropping;
		
		Boolean IsBreakpointMode;
		Boolean IsDisableEffectCache;
		Boolean IsSaveEffectSources;
		Boolean IsWarningsAreErrors;
		Boolean IsSimulateExclusiveFullscreen;
		Boolean Is3DGameMode;
		Boolean IsShowFPS;
		Boolean IsVSync;
		Boolean IsTripleBuffering;
		Boolean IsAdjustCursorSpeed;
	}
}
