namespace Magpie.Runtime
{
    enum CaptureMode {
        GraphicsCapture,
        DesktopDuplication,
        GDI,
        DwmSharedSurface
    };

    [default_interface]
    runtimeclass MagSettings
    {
        MagSettings();

        CaptureMode CaptureMode;

        Boolean IsBreakpointMode;
        Boolean IsDisableEffectCache;
        Boolean IsSaveEffectSources;
        Boolean IsWarningsAreErrors;
    }
}
