namespace Magpie.Runtime
{
    enum CaptureMode {
        GraphicsCapture,
        DesktopDuplication,
        GDI,
        DwmSharedSurface
    };

    [default_interface]
    runtimeclass MagSettings
    {
        MagSettings();

        void CopyFrom(MagSettings other);

        CaptureMode CaptureMode;

        Boolean IsBreakpointMode;
        Boolean IsDisableEffectCache;
        Boolean IsSaveEffectSources;
        Boolean IsWarningsAreErrors;
        Boolean IsSimulateExclusiveFullscreen;
        Boolean Is3DGameMode;
    }
}
