namespace Magpie.UI {
	runtimeclass AboutViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		AboutViewModel();

		String Version { get; };
		Windows.Foundation.Uri ReleaseNotesLink { get; };

		void CheckForUpdates();
		Boolean IsCheckingForUpdates { get; };

		Boolean IsAutoCheckForUpdates;
		Boolean IsCheckForPreviewUpdates;

		Boolean IsNetworkErrorWhileChecking;
		Boolean IsOtherErrorWhileChecking;
		Boolean IsNoUpdate;
		Boolean IsAvailable;

		Windows.Foundation.Uri UpdateReleaseNotesLink { get; };

		void DownloadAndInstall();
	}
}
