namespace Magpie.UI
{
    [default_interface]
    runtimeclass AboutViewModel : [default] Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        AboutViewModel();

        String Version { get; };
        void CheckForUpdate();

        Boolean IsAutoDownloadUpdates;
        Boolean IsCheckForPreviewUpdates;
    }
}
