namespace Magpie.UI {
	runtimeclass ScalingModeBoolParameter : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		ScalingModeBoolParameter(UInt32 index, String label, Boolean initValue);

		Boolean Value;
		String Label { get; };
	}

	runtimeclass ScalingModeFloatParameter : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		ScalingModeFloatParameter(UInt32 index, String label, Single initValue, Single minimum, Single maximum, Single step);

		Double Value;
		String Label { get; };
		String ValueText { get; };
		Double Minimum { get; };
		Double Maximum { get; };
		Double Step{ get; };
	}

	runtimeclass EffectParametersViewModel {
		EffectParametersViewModel();
		EffectParametersViewModel(UInt32 scalingModeIdx, UInt32 effectIdx);

		UInt32 ScalingModeIdx;
		UInt32 EffectIdx;

		IVector<IInspectable> BoolParams { get; };
		IVector<IInspectable> FloatParams { get; };
		Boolean HasBoolParams { get; };
		Boolean HasFloatParams { get; };
	}
}
