namespace Magpie.UI {
	runtimeclass HomeViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		HomeViewModel();
		
		Boolean IsCountingDown { get; };
		Single CountdownProgressRingValue { get; };
		String CountdownLabelText { get; };
		String CountdownButtonText { get; };
		Boolean IsNotRunning { get; };
		UInt32 DownCount;

		void ToggleCountdown();

		Boolean IsAutoRestore;
		Boolean IsWndToRestore { get; };
		String RestoreWndDesc { get; };

		void ActivateRestore();
		void ClearRestore();

		Boolean IsProcessElevated { get; };
		void RestartAsElevated();
		Boolean IsAlwaysRunAsElevated;
	}
}
