namespace Magpie.UI
{
	[default_interface]
	runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
	{
		MainPage();

		Microsoft.UI.Xaml.Controls.NavigationView RootNavigationView { get; };
		NewProfileViewModel NewProfileViewModel { get; };
	}
}
