namespace Magpie.UI
{
	[default_interface]
	runtimeclass ScalingType
	{
		ScalingType(String name, String desc);
		
		String Name { get; };
		String Desc { get; };
	}

	[default_interface]
	runtimeclass ScalingModesPage : Windows.UI.Xaml.Controls.Page
	{
		ScalingModesPage();

		ScalingModesViewModel ViewModel { get; };

		static IVector<IInspectable> ScalingTypes { get; };
		static Windows.Globalization.NumberFormatting.INumberFormatter2 NumberFormatter { get; };
	}
}
