namespace Magpie.UI
{
	runtimeclass ScalingModeEffectItem : [default] Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		ScalingModeEffectItem(UInt32 scalingModeIdx, UInt32 effectIdx);

		UInt32 ScalingModeIdx;
		UInt32 EffectIdx;
		String Name { get; };

		Boolean CanScale { get; };
		Boolean HasParameters { get; };

		void Remove();
		event Windows.Foundation.EventHandler<UInt32> Removed;
	}
}
