//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magpie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magpie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Lanczos&quot;,
        ///    &quot;effects&quot;: [
        ///      {
        ///        &quot;effect&quot;: &quot;Lanczos&quot;,
        ///        &quot;scale&quot;: [ -1, -1 ]
        ///      },
        ///      {
        ///        &quot;effect&quot;: &quot;AdaptiveSharpen&quot;,
        ///        &quot;curveHeight&quot;: 0.3
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;FSR&quot;,
        ///    &quot;effects&quot;: [
        ///      {
        ///        &quot;effect&quot;: &quot;FSR_EASU&quot;,
        ///        &quot;scale&quot;: [ -1, -1 ]
        ///      },
        ///      {
        ///        &quot;effect&quot;: &quot;FSR_RCAS&quot;,
        ///        &quot;sharpness&quot;: 0.87
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;FSRCNNX&quot;,
        ///    &quot;effects&quot;: [
        ///      {
        ///        &quot;effect&quot;: &quot;F [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuiltInScaleModels {
            get {
                return ResourceManager.GetString("BuiltInScaleModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Magpie]
        ///https://github.com/Blinue/Magpie
        ///---------------------------------------------------
        ///                    GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and ot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please check the log for more information..
        /// </summary>
        public static string Msg_Error_Generic {
            get {
                return ResourceManager.GetString("Msg_Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window cannot be captured using GraphicsCapture..
        /// </summary>
        public static string Msg_Error_GraphicsCapture {
            get {
                return ResourceManager.GetString("Msg_Error_GraphicsCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Runtime..
        /// </summary>
        public static string Msg_Error_Init {
            get {
                return ResourceManager.GetString("Msg_Error_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source window.
        /// </summary>
        public static string Msg_Error_Invalid_Source_Window {
            get {
                return ResourceManager.GetString("Msg_Error_Invalid_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain administrator privileges..
        /// </summary>
        public static string Msg_Error_Run_As_Admin {
            get {
                return ResourceManager.GetString("Msg_Error_Run_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This monitor does not support turning off VSync..
        /// </summary>
        public static string Msg_Error_Vsync_Off_Not_Supported {
            get {
                return ResourceManager.GetString("Msg_Error_Vsync_Off_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Method.
        /// </summary>
        public static string UI_Main_Capture_Method {
            get {
                return ResourceManager.GetString("UI_Main_Capture_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Window: .
        /// </summary>
        public static string UI_Main_Current_Window {
            get {
                return ResourceManager.GetString("UI_Main_Current_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget.
        /// </summary>
        public static string UI_Main_Forget_Current_Window {
            get {
                return ResourceManager.GetString("UI_Main_Forget_Current_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string UI_Main_Hotkey {
            get {
                return ResourceManager.GetString("UI_Main_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection Mode.
        /// </summary>
        public static string UI_Main_Injection_Mode {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection at Startup.
        /// </summary>
        public static string UI_Main_Injection_Mode_Injection_At_Startup {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_Injection_At_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Injection.
        /// </summary>
        public static string UI_Main_Injection_Mode_No_Injection {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_No_Injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection at Runtime.
        /// </summary>
        public static string UI_Main_Injection_Mode_Runtime_Injection {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_Runtime_Injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string UI_Main_Options {
            get {
                return ResourceManager.GetString("UI_Main_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Failure.
        /// </summary>
        public static string UI_Main_Parse_Failure {
            get {
                return ResourceManager.GetString("UI_Main_Parse_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale after 5s.
        /// </summary>
        public static string UI_Main_Scale_After_5S {
            get {
                return ResourceManager.GetString("UI_Main_Scale_After_5S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling Mode.
        /// </summary>
        public static string UI_Main_Scaling_Mode {
            get {
                return ResourceManager.GetString("UI_Main_Scaling_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magpie.
        /// </summary>
        public static string UI_Main_Title {
            get {
                return ResourceManager.GetString("UI_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string UI_Options_About {
            get {
                return ResourceManager.GetString("UI_Options_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string UI_Options_About_Feedback {
            get {
                return ResourceManager.GetString("UI_Options_About_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string UI_Options_About_Licenses {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string UI_Options_About_Licenses_Close {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The liceses that Magpie Uses:.
        /// </summary>
        public static string UI_Options_About_Licenses_Header {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magpie Licenses.
        /// </summary>
        public static string UI_Options_About_Licenses_Title {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL.
        /// </summary>
        public static string UI_Options_About_Project_URL {
            get {
                return ResourceManager.GetString("UI_Options_About_Project_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string UI_Options_About_Support {
            get {
                return ResourceManager.GetString("UI_Options_About_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string UI_Options_About_Thanks {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All those who have provided feedback and contributions to Magpie.
        /// </summary>
        public static string UI_Options_About_Thanks_Contributors {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All shader projects supported by Magpie.
        /// </summary>
        public static string UI_Options_About_Thanks_Shaders {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks_Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string UI_Options_About_Version {
            get {
                return ResourceManager.GetString("UI_Options_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string UI_Options_Advanced {
            get {
                return ResourceManager.GetString("UI_Options_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Texture Precision.
        /// </summary>
        public static string UI_Options_Advanced_Buffer_Precision {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Buffer_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string UI_Options_Advanced_Buffer_Precision_Default {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Buffer_Precision_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Level.
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Error {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Info {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Off {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Warn {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string UI_Options_Application {
            get {
                return ResourceManager.GetString("UI_Options_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Run as Administrator.
        /// </summary>
        public static string UI_Options_Application_Always_Run_As_Admin {
            get {
                return ResourceManager.GetString("UI_Options_Application_Always_Run_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UI_Options_Application_Language {
            get {
                return ResourceManager.GetString("UI_Options_Application_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string UI_Options_Application_Language_Default {
            get {
                return ResourceManager.GetString("UI_Options_Application_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to the System Tray at Startup.
        /// </summary>
        public static string UI_Options_Application_Minimize_To_System_Tray {
            get {
                return ResourceManager.GetString("UI_Options_Application_Minimize_To_System_Tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to the System Tray when Close the Window.
        /// </summary>
        public static string UI_Options_Application_Minimize_When_Close {
            get {
                return ResourceManager.GetString("UI_Options_Application_Minimize_When_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at Startup.
        /// </summary>
        public static string UI_Options_Application_Run_At_Startup {
            get {
                return ResourceManager.GetString("UI_Options_Application_Run_At_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will be applied after restarting Magpie..
        /// </summary>
        public static string UI_Options_Common_Restart_To_Apply {
            get {
                return ResourceManager.GetString("UI_Options_Common_Restart_To_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust cursor speed while zoomed.
        /// </summary>
        public static string UI_Options_Scale_Adjust_Cursor_Speed {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Adjust_Cursor_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable round corner of window while zoomed.
        /// </summary>
        public static string UI_Options_Scale_Disable_Round_Corner {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Disable_Round_Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Rate.
        /// </summary>
        public static string UI_Options_Scale_Frame_Rate {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Frame_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limiter.
        /// </summary>
        public static string UI_Options_Scale_Frame_Rate_Limiter {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Frame_Rate_Limiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Limited.
        /// </summary>
        public static string UI_Options_Scale_Frame_Rate_Not_Limited {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Frame_Rate_Not_Limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Vsync.
        /// </summary>
        public static string UI_Options_Scale_No_VSync {
            get {
                return ResourceManager.GetString("UI_Options_Scale_No_VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Scale Config.
        /// </summary>
        public static string UI_Options_Scale_Open_Scale_Config {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Open_Scale_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore full screen when source window loses focus.
        /// </summary>
        public static string UI_Options_Scale_Restore_Full_Screen {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Restore_Full_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Frame Rate.
        /// </summary>
        public static string UI_Options_Scale_Show_Frame_Rate {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Show_Frame_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSync.
        /// </summary>
        public static string UI_Options_Scale_VSync {
            get {
                return ResourceManager.GetString("UI_Options_Scale_VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magpie Options.
        /// </summary>
        public static string UI_Options_Title {
            get {
                return ResourceManager.GetString("UI_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string UI_Options_Zoom {
            get {
                return ResourceManager.GetString("UI_Options_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string UI_SysTray_Exit {
            get {
                return ResourceManager.GetString("UI_SysTray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window.
        /// </summary>
        public static string UI_SysTray_Main_Window {
            get {
                return ResourceManager.GetString("UI_SysTray_Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string UI_SysTray_Options {
            get {
                return ResourceManager.GetString("UI_SysTray_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale after 5s.
        /// </summary>
        public static string UI_SysTray_Scale_After_5S {
            get {
                return ResourceManager.GetString("UI_SysTray_Scale_After_5S", resourceCulture);
            }
        }
    }
}
