//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magpie.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magpie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Caption {
            get {
                return ResourceManager.GetString("Msg_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to capture, please change the capture method. 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Failed_To_Capture {
            get {
                return ResourceManager.GetString("Msg_Error_Failed_To_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This window is too small to crop. 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Failed_To_Crop {
            get {
                return ResourceManager.GetString("Msg_Error_Failed_To_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred, please check logs for more information. 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Generic {
            get {
                return ResourceManager.GetString("Msg_Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to initialize Runtime. 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Init {
            get {
                return ResourceManager.GetString("Msg_Error_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid source window 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Invalid_Source_Window {
            get {
                return ResourceManager.GetString("Msg_Error_Invalid_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to obtain administrator privileges. 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Run_As_Admin {
            get {
                return ResourceManager.GetString("Msg_Error_Run_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This window is too large to capture. 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Src_Too_Large {
            get {
                return ResourceManager.GetString("Msg_Error_Src_Too_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This monitor does not support turning off VSync. 的本地化字符串。
        /// </summary>
        public static string Msg_Error_Vsync_Off_Not_Supported {
            get {
                return ResourceManager.GetString("Msg_Error_Vsync_Off_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture Method 的本地化字符串。
        /// </summary>
        public static string UI_Main_Capture_Method {
            get {
                return ResourceManager.GetString("UI_Main_Capture_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Window:  的本地化字符串。
        /// </summary>
        public static string UI_Main_Current_Window {
            get {
                return ResourceManager.GetString("UI_Main_Current_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget 的本地化字符串。
        /// </summary>
        public static string UI_Main_Forget_Current_Window {
            get {
                return ResourceManager.GetString("UI_Main_Forget_Current_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey 的本地化字符串。
        /// </summary>
        public static string UI_Main_Hotkey {
            get {
                return ResourceManager.GetString("UI_Main_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Injection Mode 的本地化字符串。
        /// </summary>
        public static string UI_Main_Injection_Mode {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Injection at Startup 的本地化字符串。
        /// </summary>
        public static string UI_Main_Injection_Mode_Injection_At_Startup {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_Injection_At_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Injection 的本地化字符串。
        /// </summary>
        public static string UI_Main_Injection_Mode_No_Injection {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_No_Injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Injection at Runtime 的本地化字符串。
        /// </summary>
        public static string UI_Main_Injection_Mode_Runtime_Injection {
            get {
                return ResourceManager.GetString("UI_Main_Injection_Mode_Runtime_Injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string UI_Main_Options {
            get {
                return ResourceManager.GetString("UI_Main_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parse Failure 的本地化字符串。
        /// </summary>
        public static string UI_Main_Parse_Failure {
            get {
                return ResourceManager.GetString("UI_Main_Parse_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale after 5s 的本地化字符串。
        /// </summary>
        public static string UI_Main_Scale_After_5S {
            get {
                return ResourceManager.GetString("UI_Main_Scale_After_5S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scaling Mode 的本地化字符串。
        /// </summary>
        public static string UI_Main_Scaling_Mode {
            get {
                return ResourceManager.GetString("UI_Main_Scaling_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magpie 的本地化字符串。
        /// </summary>
        public static string UI_Main_Title {
            get {
                return ResourceManager.GetString("UI_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string UI_Options_About {
            get {
                return ResourceManager.GetString("UI_Options_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Feedback {
            get {
                return ResourceManager.GetString("UI_Options_About_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Licenses 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Licenses {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Licenses_Close {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The liceses that Magpie Uses: 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Licenses_Header {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magpie Licenses 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Licenses_Title {
            get {
                return ResourceManager.GetString("UI_Options_About_Licenses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project URL 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Project_URL {
            get {
                return ResourceManager.GetString("UI_Options_About_Project_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Support {
            get {
                return ResourceManager.GetString("UI_Options_About_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Thanks {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All those who have provided feedback and contributions to Magpie 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Thanks_Contributors {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All shader projects supported by Magpie 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Thanks_Shaders {
            get {
                return ResourceManager.GetString("UI_Options_About_Thanks_Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string UI_Options_About_Version {
            get {
                return ResourceManager.GetString("UI_Options_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced {
            get {
                return ResourceManager.GetString("UI_Options_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breakpoint Mode 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Breakpoint_Mode {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Breakpoint_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugging 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Debugging {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable DirectFlip 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Disable_DirectFlip {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Disable_DirectFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Effect Cache 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Disable_Effect_Cache {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Disable_Effect_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Logging {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging Level 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Error {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Info {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Off {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warn 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Logging_Level_Warn {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Logging_Level_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Logs Folder 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Open_Logs_Folder {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Open_Logs_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Sources when Resolving Effects 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Save_Effect_Sources {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Save_Effect_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show All Capture Methods 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Show_All_Capture_Methods {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Show_All_Capture_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Debugging Options 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Show_Debugging_Options {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Show_Debugging_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulate Exclusive Fullscreen 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Simulate_Exclusive_Fullscreen {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Simulate_Exclusive_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Treat Warnings as Errors when Compiling Shaders 的本地化字符串。
        /// </summary>
        public static string UI_Options_Advanced_Warnings_Are_Errors {
            get {
                return ResourceManager.GetString("UI_Options_Advanced_Warnings_Are_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application {
            get {
                return ResourceManager.GetString("UI_Options_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Run as Administrator 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Always_Run_As_Admin {
            get {
                return ResourceManager.GetString("UI_Options_Application_Always_Run_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop the Title Bar of UWP Windows 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Crop_Title_Bar_Of_UWP {
            get {
                return ResourceManager.GetString("UI_Options_Application_Crop_Title_Bar_Of_UWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Bottom {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Left {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Right {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Top {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit: pixel 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Custom_Cropping_Unit {
            get {
                return ResourceManager.GetString("UI_Options_Application_Custom_Cropping_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Custom Cropping 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Enable_Custom_Cropping {
            get {
                return ResourceManager.GetString("UI_Options_Application_Enable_Custom_Cropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Language {
            get {
                return ResourceManager.GetString("UI_Options_Application_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Language_Default {
            get {
                return ResourceManager.GetString("UI_Options_Application_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to the System Tray at Startup 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Minimize_To_System_Tray {
            get {
                return ResourceManager.GetString("UI_Options_Application_Minimize_To_System_Tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to the System Tray when Close the Window 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Minimize_When_Close {
            get {
                return ResourceManager.GetString("UI_Options_Application_Minimize_When_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run at Startup 的本地化字符串。
        /// </summary>
        public static string UI_Options_Application_Run_At_Startup {
            get {
                return ResourceManager.GetString("UI_Options_Application_Run_At_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This change will be applied after restarting Magpie. 的本地化字符串。
        /// </summary>
        public static string UI_Options_Common_Restart_To_Apply {
            get {
                return ResourceManager.GetString("UI_Options_Common_Restart_To_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics Adapter 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Adapter {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Adapter_Default {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Adapter_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust Cursor Speed while Zoomed 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Adjust_Cursor_Speed {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Adjust_Cursor_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cursor 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confine the Cursor in 3D Games 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Confine_In_3D_Games {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Confine_In_3D_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not Draw the Cursor 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Do_Not_Draw {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Do_Not_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interpolation Mode 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Interpolation_Mode {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Interpolation_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilinear 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Interpolation_Mode_Bilinear {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Interpolation_Mode_Bilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nearest 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Interpolation_Mode_Nearest {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Interpolation_Mode_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same as Source Window 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Same_As_Source_Window {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Same_As_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom Factor of the Cursor 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Cursor_Zoom_Factor {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Cursor_Zoom_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Additional Latency to Improve Performance 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Disable_Low_Latency {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Disable_Low_Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Round Corner while Zoomed 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Disable_Round_Corner {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Disable_Round_Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Window Resizing while Zoomed 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Disable_Window_Resizing {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Disable_Window_Resizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple Monitors 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use All Monitors 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors_All {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the Monitors that the Source Window Intersects 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors_Intersect {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors_Intersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the Monitor Nearest to the Source Window 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Multiple_Monitors_Nearest {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Multiple_Monitors_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Scale Config 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Open_Scale_Config {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Open_Scale_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Fullscreen when Source Window Regains Focus 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Restore_Full_Screen {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Restore_Full_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source Window 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_Source_Window {
            get {
                return ResourceManager.GetString("UI_Options_Scale_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vsync 的本地化字符串。
        /// </summary>
        public static string UI_Options_Scale_VSync {
            get {
                return ResourceManager.GetString("UI_Options_Scale_VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magpie Options 的本地化字符串。
        /// </summary>
        public static string UI_Options_Title {
            get {
                return ResourceManager.GetString("UI_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        public static string UI_Options_Zoom {
            get {
                return ResourceManager.GetString("UI_Options_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string UI_SysTray_Exit {
            get {
                return ResourceManager.GetString("UI_SysTray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Window 的本地化字符串。
        /// </summary>
        public static string UI_SysTray_Main_Window {
            get {
                return ResourceManager.GetString("UI_SysTray_Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string UI_SysTray_Options {
            get {
                return ResourceManager.GetString("UI_SysTray_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale after 5s 的本地化字符串。
        /// </summary>
        public static string UI_SysTray_Scale_After_5S {
            get {
                return ResourceManager.GetString("UI_SysTray_Scale_After_5S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magpie
        ///Hotkey: {0}
        ///Scaling Mode: {1}
        ///Capture Method: {2} 的本地化字符串。
        /// </summary>
        public static string UI_SysTray_Text {
            get {
                return ResourceManager.GetString("UI_SysTray_Text", resourceCulture);
            }
        }
    }
}
