//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magpie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magpie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Lanczos&quot;,
        ///    &quot;model&quot;: [
        ///      {
        ///        &quot;module&quot;: &quot;Common&quot;,
        ///        &quot;effect&quot;: &quot;lanczos&quot;,
        ///        &quot;scale&quot;: [ -1, -1 ],
        ///        &quot;ARStrength&quot;: 0.7
        ///      },
        ///      {
        ///        &quot;module&quot;: &quot;Common&quot;,
        ///        &quot;effect&quot;: &quot;adaptiveSharpen&quot;,
        ///        &quot;curveHeight&quot;: 0.6
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;RAVU&quot;,
        ///    &quot;model&quot;: [
        ///      {
        ///        &quot;module&quot;: &quot;RAVU&quot;,
        ///        &quot;effect&quot;: &quot;RAVUZoom&quot;,
        ///        &quot;scale&quot;: [ -1, -1 ]
        ///      },
        ///      {
        ///        &quot;module&quot;: &quot;Anime4K&quot;,
        ///        &quot;effect&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuiltInScaleModels {
            get {
                return ResourceManager.GetString("BuiltInScaleModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ / WinRT.
        /// </summary>
        public static string Cpp_WinRT {
            get {
                return ResourceManager.GetString("Cpp_WinRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyHook.
        /// </summary>
        public static string EasyHook {
            get {
                return ResourceManager.GetString("EasyHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Magpie]
        ///https://github.com/Blinue/Magpie
        ///---------------------------------------------------
        ///                    GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and ot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The liceses that Magpie Uses:.
        /// </summary>
        public static string Magpie_和它使用的开源软件的许可 {
            get {
                return ResourceManager.GetString("Magpie_和它使用的开源软件的许可", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magpie Open Source Licenses.
        /// </summary>
        public static string Magpie_开源许可 {
            get {
                return ResourceManager.GetString("Magpie_开源许可", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All shader projects supported by Magpie.
        /// </summary>
        public static string Magpie_移植的所有优秀着色器项目 {
            get {
                return ResourceManager.GetString("Magpie_移植的所有优秀着色器项目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magpie Options.
        /// </summary>
        public static string Magpie_选项 {
            get {
                return ResourceManager.GetString("Magpie_选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio.
        /// </summary>
        public static string Visual_Studio {
            get {
                return ResourceManager.GetString("Visual_Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Injection.
        /// </summary>
        public static string 不注入 {
            get {
                return ResourceManager.GetString("不注入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string 关于 {
            get {
                return ResourceManager.GetString("关于", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string 反馈 {
            get {
                return ResourceManager.GetString("反馈", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection at Startup.
        /// </summary>
        public static string 启动时注入 {
            get {
                return ResourceManager.GetString("启动时注入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore full screen when source window loses focus.
        /// </summary>
        public static string 如果源窗口失去焦点_则在它重获焦点时恢复全屏 {
            get {
                return ResourceManager.GetString("如果源窗口失去焦点_则在它重获焦点时恢复全屏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string 应用程序 {
            get {
                return ResourceManager.GetString("应用程序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at Startup.
        /// </summary>
        public static string 开机启动 {
            get {
                return ResourceManager.GetString("开机启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimise to the System Tray at Startup.
        /// </summary>
        public static string 开机启动时最小化到系统托盘 {
            get {
                return ResourceManager.GetString("开机启动时最小化到系统托盘", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Licenses.
        /// </summary>
        public static string 开源许可 {
            get {
                return ResourceManager.GetString("开源许可", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Window.
        /// </summary>
        public static string 当前窗口 {
            get {
                return ResourceManager.GetString("当前窗口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All those who have provided feedback and contributions to Magpie.
        /// </summary>
        public static string 所有为Magpie提供反馈与贡献的人 {
            get {
                return ResourceManager.GetString("所有为Magpie提供反馈与贡献的人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Scale configuration file.
        /// </summary>
        public static string 打开缩放配置 {
            get {
                return ResourceManager.GetString("打开缩放配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mode.
        /// </summary>
        public static string 抓取模式 {
            get {
                return ResourceManager.GetString("抓取模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string 支持 {
            get {
                return ResourceManager.GetString("支持", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Level.
        /// </summary>
        public static string 日志级别 {
            get {
                return ResourceManager.GetString("日志级别", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Frame Rate.
        /// </summary>
        public static string 显示帧率 {
            get {
                return ResourceManager.GetString("显示帧率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string 热键 {
            get {
                return ResourceManager.GetString("热键", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string 版本 {
            get {
                return ResourceManager.GetString("版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string 确定 {
            get {
                return ResourceManager.GetString("确定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in after 5s.
        /// </summary>
        public static string 秒后缩放 {
            get {
                return ResourceManager.GetString("秒后缩放", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string 缩放 {
            get {
                return ResourceManager.GetString("缩放", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust cursor scale while zoomed.
        /// </summary>
        public static string 缩放时调整光标速度 {
            get {
                return ResourceManager.GetString("缩放时调整光标速度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling Mode.
        /// </summary>
        public static string 缩放模式 {
            get {
                return ResourceManager.GetString("缩放模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Failure.
        /// </summary>
        public static string 解析失败 {
            get {
                return ResourceManager.GetString("解析失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string 语言 {
            get {
                return ResourceManager.GetString("语言", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Injection.
        /// </summary>
        public static string 运行时注入 {
            get {
                return ResourceManager.GetString("运行时注入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection Mode.
        /// </summary>
        public static string 进程注入 {
            get {
                return ResourceManager.GetString("进程注入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string 选项 {
            get {
                return ResourceManager.GetString("选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL.
        /// </summary>
        public static string 项目地址 {
            get {
                return ResourceManager.GetString("项目地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string 高级 {
            get {
                return ResourceManager.GetString("高级", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string 鸣谢 {
            get {
                return ResourceManager.GetString("鸣谢", resourceCulture);
            }
        }
    }
}
