#include "LoggerHelper.idl"
#include "MainPage.idl"
#include "SettingItem.idl"
#include "SettingsGroup.idl"
#include "MicaBrush.idl"
#include "HomeViewModel.idl"
#include "SettingsViewModel.idl"
#include "ScalingProfileViewModel.idl"
#include "AboutPage.idl"
#include "HomePage.idl"
#include "SettingsPage.idl"
#include "KeyVisual.idl"
#include "ShortcutControl.idl"
#include "ShortcutDialog.idl"
#include "NewProfileDialog.idl"
#include "ScalingModesPage.idl"
#include "ScalingProfilePage.idl"


namespace Magpie.App {
	enum HotkeyAction {
		Scale,
		Overlay,
		COUNT_OR_NONE
	};

	enum HotkeyError {
		NoError,
		Invalid,
		Occupied
	};

	[default_interface]
	runtimeclass App : Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication {
		App();

		void OnClose();

		Boolean Initialize(UInt64 hwndHost, UInt64 pWndRect, UInt64 pIsWndMaximized);

		UInt64 HwndHost { get; };

		Boolean IsHostWndFocused { get; };
		event Windows.Foundation.EventHandler<Boolean> HostWndFocusChanged;
		void OnHostWndFocusChanged(Boolean isFocused);

		void OnHotkeyPressed(HotkeyAction action);
	}
}
