#include "DummyTemplate.idl"
#include "Settings.idl"
#include "MainPage.idl"
#include "SettingItem.idl"
#include "SettingsGroup.idl"
#include "MicaBrush.idl"
#include "AboutPage.idl"
#include "HomePage.idl"
#include "SettingsPage.idl"
#include "KeyVisual.idl"


namespace Magpie{
	[default_interface]
	runtimeclass App : Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication {
		App();

		void OnClose();

		Boolean Initialize(Settings settings);

		Settings Settings{ get; };
	}
}
