#include "LoggerHelper.idl"
#include "DummyTemplate.idl"
#include "HotkeySettings.idl"
#include "Settings.idl"
#include "MainPage.idl"
#include "SettingItem.idl"
#include "SettingsGroup.idl"
#include "MicaBrush.idl"
#include "AboutPage.idl"
#include "HomePage.idl"
#include "SettingsPage.idl"
#include "KeyVisual.idl"
#include "HotkeyManager.idl"
#include "ShortcutControl.idl"
#include "ShortcutDialogContent.idl"
#include "MagService.idl"
#include "ScalingModesPage.idl"
#include "ScalingConfigPage.idl"


namespace Magpie.App {
	[default_interface]
	runtimeclass App : Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication {
		App();

		void OnClose();

		Boolean Initialize(Settings settings, UInt64 hwndHost);

		Settings Settings { get; };
		HotkeyManager HotkeyManager { get; };
		Magpie.Runtime.MagRuntime MagRuntime{ get; };
		MagService MagService { get; };

		UInt64 HwndHost { get; };

		Boolean IsHostWndFocused { get; };
		event Windows.Foundation.EventHandler<Boolean> HostWndFocusChanged;
		void OnHostWndFocusChanged(Boolean isFocused);
	}
}
