namespace Magpie.App
{
	[default_interface]
	runtimeclass HotkeySettings 
	{
		HotkeySettings();

		Boolean Win;
		Boolean Ctrl;
		Boolean Alt;
		Boolean Shift;

		UInt32 Code;

		Boolean Check();
		
		IVector<Object> GetKeyList();
	}
}
