namespace Magpie.App
{
	[default_interface]
	runtimeclass HotkeySettings 
	{
		HotkeySettings();

		void CopyFrom(HotkeySettings other);

		Boolean Win;
		Boolean Ctrl;
		Boolean Alt;
		Boolean Shift;

		UInt32 Code;

		Boolean Check();
		Boolean IsEmpty();
		void Clear();
		Boolean Equals(HotkeySettings other);

		Boolean FromString(String str);
		String ToString();
		
		IVector<Object> GetKeyList();
	}
}
