namespace Magpie.App
{
	[default_interface]
	runtimeclass MagService 
	{
		MagService(Settings settings, Magpie.Runtime.MagRuntime magRuntime, Windows.UI.Core.CoreDispatcher dispatcher);

		UInt64 WndToRestore { get; };
		event Windows.Foundation.EventHandler<UInt64> WndToRestoreChanged;
	}
}
