namespace Magpie.App
{
	[default_interface]
	runtimeclass MagService 
	{
		MagService(Settings settings, Magpie.Runtime.MagRuntime magRuntime);

		void StartCountdown();
		void StopCountdown();

		Boolean IsCountingDown { get; };
		event Windows.Foundation.EventHandler<Boolean> IsCountingDownChanged;
		UInt32 TickingDownCount { get; };
		Single CountdownLeft { get; };
		event Windows.Foundation.EventHandler<Single> CountdownTick;

		UInt64 WndToRestore { get; };
		event Windows.Foundation.EventHandler<UInt64> WndToRestoreChanged;
		void ClearWndToRestore();
	}
}
