namespace Magpie.App
{
    runtimeclass NewProfileDialog : Windows.UI.Xaml.Controls.UserControl, [default] Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        NewProfileDialog();

        IVector<IInspectable> CandidateWindows { get; };
    }
}
