namespace Magpie.App
{
    [Windows.UI.Xaml.Data.Bindable]
    runtimeclass CandidateWindow : [default] Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        CandidateWindow(UInt64 hWnd, Boolean preferLargeIcon);

        UInt64 HWnd { get; };
        String Title { get; };
        Object Icon { get; };
        String DefaultProfileName { get; };
    }

    runtimeclass NewProfileDialog : Windows.UI.Xaml.Controls.UserControl, [default] Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        NewProfileDialog();

        IVector<CandidateWindow> CandidateWindows { get; };
        Int32 WindowIndex;
        IVector<IInspectable> Profiles { get; };
        Int32 ProfileIndex;
    }
}
