namespace Magpie.App
{
    [Windows.UI.Xaml.Markup.ContentProperty("MainContent")]
    runtimeclass PageFrame : Windows.UI.Xaml.Controls.UserControl, [default] Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        PageFrame();

        String Title;
        Windows.UI.Xaml.Controls.IconElement Icon;
        Object MainContent;
    }
}
