namespace Magpie
{
    [default_interface]
    [Windows.UI.Xaml.Markup.ContentProperty("MainContent")]
    runtimeclass PageFrame : Windows.UI.Xaml.Controls.UserControl
    {
        PageFrame();

        String Title;
        Object MainContent;
    }
}
