namespace Magpie.App
{
	[default_interface]
	runtimeclass ScalingProfileViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		ScalingProfileViewModel(UInt32 profileId);

		String Name;
		Int32 CaptureMode;
		Boolean Is3DGameMode;
		Int32 MultiMonitorUsage;

		IVector<IInspectable> GraphicsAdapters { get; };
		Int32 GraphicsAdapter;

		Boolean IsShowFPS;
		Boolean IsVSync;
		Boolean IsTripleBuffering;
		Boolean IsDisableWindowResizing;
		Boolean IsReserveTitleBar;

		Boolean IsCroppingEnabled;
		Double CroppingLeft;
		Double CroppingTop;
		Double CroppingRight;
		Double CroppingBottom;

		Boolean IsAdjustCursorSpeed;
	}
}
