namespace Magpie
{
	[default_interface]
	[Windows.UI.Xaml.TemplateVisualState("Normal", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("Disabled", "CommonStates")]
	runtimeclass SettingsGroup : Windows.UI.Xaml.Controls.ItemsControl
	{
		SettingsGroup();

		String MyHeader;
		Object Description;
	}

	runtimeclass SettingsGroupAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
	{
		SettingsGroupAutomationPeer(SettingsGroup owner);

		String GetNameCore();
	}
}
