namespace Magpie.App
{
	enum HotkeyAction {
		Scale,
		Overlay,
		COUNT_OR_NONE
	};

	[default_interface]
	runtimeclass Settings 
	{
		Settings();

		Boolean Initialize();

		Boolean Save();

		Boolean IsPortableMode;
		String WorkingDir{ get; };

		Int32 Theme;
		event Windows.Foundation.EventHandler<Int32> ThemeChanged;

		Windows.Foundation.Rect WindowRect;
		Boolean IsWindowMaximized;

		HotkeySettings GetHotkey(HotkeyAction action);
		void SetHotkey(HotkeyAction action, HotkeySettings value);
		event Windows.Foundation.EventHandler<HotkeyAction> HotkeyChanged;

		Boolean IsAutoRestore;
		event Windows.Foundation.EventHandler<Boolean> IsAutoRestoreChanged;

		UInt32 DownCount;
		event Windows.Foundation.EventHandler<UInt32> DownCountChanged;

		Magpie.Runtime.MagSettings GetMagSettings(UInt64 hWnd);

		Boolean IsBreakpointMode;
		Boolean IsDisableEffectCache;
		Boolean IsSaveEffectSources;
		Boolean IsWarningsAreErrors;
	}
}
