namespace Magpie
{
    [default_interface]
    [Windows.UI.Xaml.Markup.ContentProperty("Children")]
    runtimeclass SettingsGroup1 : Windows.UI.Xaml.Controls.UserControl
    {
        SettingsGroup1();

        Windows.UI.Xaml.Controls.UIElementCollection Children;
    }
}
