namespace Magpie
{
	[Windows.UI.Xaml.TemplateVisualState("Normal", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("Disabled", "CommonStates")]
	runtimeclass SettingItem : Windows.UI.Xaml.Controls.ContentControl
	{
		SettingItem();

		void OnApplyTemplate();

		String MyHeader;
		Object Description;
		Object Icon;
		Object ActionContent;
	}
}
