namespace Magpie.App
{
	runtimeclass ShortcutControl : Windows.UI.Xaml.Controls.UserControl,[default] Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		ShortcutControl();

		Boolean IsError { get; };
	}
}
