namespace Magpie
{
    [default_interface]
    runtimeclass ShortcutDialogContent : Windows.UI.Xaml.Controls.UserControl
    {
        ShortcutDialogContent();

        Boolean IsError;
        IVector<Object> Keys;
    }
}
