namespace Magpie {
    // true -> Visibility::Collapsed
    // false -> Visibility::Visible
    runtimeclass BoolToNegativeVisibilityConverter : [default] Windows.UI.Xaml.Data.IValueConverter {
        BoolToNegativeVisibilityConverter();
    }
}
