namespace Magpie {
	runtimeclass HomeViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		Boolean ShowUpdateCard;
		String UpdateCardTitle { get; };
		Boolean IsAutoCheckForUpdates;
		void DownloadAndInstall();
		void ReleaseNotes();
		void RemindMeLater();
		
		Boolean IsTimerOn { get; };
		Double TimerProgressRingValue { get; };
		String TimerLabelText { get; };
		String TimerButtonText { get; };
		Boolean IsNotRunning { get; };
		UInt32 Delay;

		void ToggleTimer();

		Boolean IsTouchSupportEnabled;
		Windows.Foundation.Uri TouchSupportLearnMoreUrl { get; };
		Boolean IsShowTouchSupportInfoBar { get; };

		Boolean IsAllowScalingMaximized;
		Boolean IsInlineParams;
		Boolean IsSimulateExclusiveFullscreen;
		static IVector<IInspectable> MinFrameRateOptions { get; };
		Int32 MinFrameRateIndex;

		Boolean IsDeveloperMode;
		Boolean IsDebugMode;
		Boolean IsBenchmarkMode;
		Boolean IsEffectCacheDisabled;
		Boolean IsFontCacheDisabled;
		Boolean IsSaveEffectSources;
		Boolean IsWarningsAreErrors;
		Boolean IsFP16Disabled;
		Int32 DuplicateFrameDetectionMode;
		Boolean IsDynamicDection { get; };
		Boolean IsStatisticsForDynamicDetectionEnabled;
	}
}
