namespace Magpie {
	runtimeclass IsEqualStateTrigger : Windows.UI.Xaml.StateTriggerBase {
		IsEqualStateTrigger();
		
		Object Value;
		Object To;

		static Windows.UI.Xaml.DependencyProperty ValueProperty { get; };
		static Windows.UI.Xaml.DependencyProperty ToProperty { get; };
	}
}
