namespace Magpie {
	runtimeclass IsNullStateTrigger : Windows.UI.Xaml.StateTriggerBase {
		IsNullStateTrigger();
		
		Object Value;
		static Windows.UI.Xaml.DependencyProperty ValueProperty { get; };
	}
}
