namespace Magpie {
	enum VisualType {
		Small,
		SmallOutline,
		Large
	};

	[Windows.UI.Xaml.TemplateVisualState("Normal", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("Disabled", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("Default", "StateStates")]
	[Windows.UI.Xaml.TemplateVisualState("Error", "StateStates")]
	runtimeclass KeyVisual : Windows.UI.Xaml.Controls.Control, Windows.UI.Xaml.Data.INotifyPropertyChanged {
		KeyVisual();

		Int32 Key;
		VisualType VisualType;
		Boolean IsError;
	}

	[default_interface]
	runtimeclass KeyVisualStyle : Windows.UI.Xaml.ResourceDictionary {
		KeyVisualStyle();
	}
}
