namespace Magpie {
	runtimeclass NewProfileViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		NewProfileViewModel();

		void PrepareForOpen(UInt32 dpi, Boolean isLightTheme);

		IVector<IInspectable> CandidateWindows { get; };
		Int32 CandidateWindowIndex;
		String Name;
		IVector<IInspectable> Profiles { get; };
		Int32 ProfileIndex;
		Boolean IsConfirmButtonEnabled { get; };
		Boolean IsNoCandidateWindow { get; };
		Boolean IsAnyCandidateWindow { get; };

		void Confirm();
	}
}
