namespace Magpie {
	[Windows.UI.Xaml.Markup.ContentProperty("MainContent")]
	runtimeclass PageFrame : Windows.UI.Xaml.Controls.UserControl {
		PageFrame();

		static Windows.UI.Xaml.DependencyProperty TitleProperty { get; };
		static Windows.UI.Xaml.DependencyProperty IconProperty { get; };
		static Windows.UI.Xaml.DependencyProperty HeaderActionProperty { get; };
		static Windows.UI.Xaml.DependencyProperty MainContentProperty { get; };

		String Title;
		Windows.UI.Xaml.Controls.IconElement Icon;
		Windows.UI.Xaml.FrameworkElement HeaderAction;
		Object MainContent;

		Windows.UI.Xaml.Controls.ScrollViewer ScrollViewer { get; };
	}
}
