namespace Magpie {
	runtimeclass ProfilePage : Windows.UI.Xaml.Controls.Page {
		ProfilePage();

		ProfileViewModel ViewModel { get; };

		static Windows.Globalization.NumberFormatting.INumberFormatter2 NumberFormatter { get; };

		// https://github.com/microsoft/microsoft-ui-xaml/issues/7579
		void UnloadObject(Windows.UI.Xaml.DependencyObject object);
	}
}
