namespace Magpie {
	runtimeclass ScalingModesPage : Windows.UI.Xaml.Controls.Page {
		ScalingModesPage();

		ScalingModesViewModel ViewModel { get; };

		// https://github.com/microsoft/microsoft-ui-xaml/issues/7579
		void UnloadObject(Windows.UI.Xaml.DependencyObject object);
	}
}
