namespace Magpie {
    runtimeclass ScalingModesViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
        void Export();
        void Import();
        
        IObservableVector<IInspectable> ScalingModes { get; };

        String NewScalingModeName;
        IVector<IInspectable> NewScalingModeCopyFromList { get; };
        Int32 NewScalingModeCopyFrom;
        Boolean IsAddButtonEnabled { get; };
    }
}
