namespace Magpie{
	enum ContentAlignment {
		// The Content is aligned to the right. Default state.
		Right,
		// The Content is left-aligned while the Header, HeaderIcon and Description are collapsed.
		// This is commonly used for Content types such as CheckBoxes, RadioButtons and custom layouts.
		Left,
		// The Content is vertically aligned.
		Vertical
	};

	[Windows.UI.Xaml.TemplateVisualState("NormalState", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("PointerOverState", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("PressedState", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("DisabledState", "CommonStates")]
	
	[Windows.UI.Xaml.TemplateVisualState("RightState", "ContentAlignmentStates")]
	[Windows.UI.Xaml.TemplateVisualState("RightWrappedState", "ContentAlignmentStates")]
	[Windows.UI.Xaml.TemplateVisualState("RightWrappedNoIconState", "ContentAlignmentStates")]
	[Windows.UI.Xaml.TemplateVisualState("LeftState", "ContentAlignmentStates")]
	[Windows.UI.Xaml.TemplateVisualState("VerticalState", "ContentAlignmentStates")]
	
	[Windows.UI.Xaml.TemplateVisualState("NoContentSpacingState", "ContentSpacingStates")]
	[Windows.UI.Xaml.TemplateVisualState("ContentSpacingState", "ContentSpacingStates")]
	runtimeclass SettingsCard : Windows.UI.Xaml.Controls.Primitives.ButtonBase {
		SettingsCard();

		static Windows.UI.Xaml.DependencyProperty HeaderProperty { get; };
		static Windows.UI.Xaml.DependencyProperty DescriptionProperty { get; };
		static Windows.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
		static Windows.UI.Xaml.DependencyProperty ActionIconProperty { get; };
		static Windows.UI.Xaml.DependencyProperty IsClickEnabledProperty { get; };
		static Windows.UI.Xaml.DependencyProperty ContentAlignmentProperty { get; };
		static Windows.UI.Xaml.DependencyProperty IsActionIconVisibleProperty { get; };
		static Windows.UI.Xaml.DependencyProperty IsWrapEnabledProperty { get; };

		Object Header;
		Object Description;
		Windows.UI.Xaml.Controls.IconElement HeaderIcon;
		Windows.UI.Xaml.Controls.IconElement ActionIcon;
		Boolean IsClickEnabled;
		ContentAlignment ContentAlignment;
		Boolean IsActionIconVisible;
		Boolean IsWrapEnabled;
	}

	[default_interface]
	runtimeclass SettingsCardStyle : Windows.UI.Xaml.ResourceDictionary {
		SettingsCardStyle();
	}
}
