namespace Magpie {
	runtimeclass SettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		IVector<IInspectable> Languages { get; };
		Int32 Language;
		Boolean RequireRestart { get; };
		void Restart();

		Int32 Theme;
		Boolean IsRunAtStartup;
		Boolean IsPortableMode;
		void OpenConfigLocation();
		Boolean IsShowNotifyIcon;

		Boolean IsProcessElevated { get; };
		Boolean IsAlwaysRunAsAdmin;

		Boolean IsOnnxRuntimeSupported { get; };
		Boolean IsOnnxRuntimeInstalled { get; };
		Boolean IsOnnxRuntimeBusy { get; };
		Boolean IsOnnxRuntimeError { get; };
		Boolean IsOnnxRuntimeRestartRequired { get; };
		Double OnnxRuntimeDownloadProgress { get; };
		Boolean IsOnnxRuntimeProgressIndeterminate { get; };
		void DownloadOnnxRuntime();
		void CancelOnnxRuntimeDownload();
		void OpenModelsLocation();
	}
}
