namespace Magpie {
	runtimeclass SettingsPage : Windows.UI.Xaml.Controls.Page {
		SettingsPage();

		SettingsViewModel ViewModel { get; };

		// https://github.com/microsoft/microsoft-ui-xaml/issues/7579
		void UnloadObject(Windows.UI.Xaml.DependencyObject object);
	}
}
