namespace Magpie {
	enum ShortcutError {
		NoError,
		Invalid,
		Occupied
	};

	runtimeclass ShortcutDialog : Windows.UI.Xaml.Controls.Grid {
		ShortcutDialog();

		ShortcutError Error;
		IVector<Object> Keys;
	}
}
