namespace Magpie {
	enum ShortcutAction {
		Scale,
		WindowedModeScale,
		Overlay,
		COUNT_OR_NONE
	};

	runtimeclass ShortcutControl : Windows.UI.Xaml.Controls.Grid, Windows.UI.Xaml.Data.INotifyPropertyChanged {
		ShortcutControl();

		ShortcutAction Action;
		String Title;
	}
}
