namespace Magpie {
    static runtimeclass TextBlockHelper {
        static Windows.UI.Xaml.DependencyProperty IsAutoTooltipEnabledProperty{ get; };
        static Boolean GetIsAutoTooltipEnabled(Windows.UI.Xaml.DependencyObject target);
        static void SetIsAutoTooltipEnabled(Windows.UI.Xaml.DependencyObject target, Boolean value);
    }
}
