namespace Magpie.App {
	runtimeclass AboutViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		AboutViewModel();

		Windows.UI.Xaml.Media.Imaging.SoftwareBitmapSource Logo { get; };

		String Version { get; };

		Boolean IsDeveloperMode;

		void CheckForUpdates();
		Boolean IsCheckingForUpdates { get; };
		Boolean IsCheckForUpdatesButtonEnabled { get; };

		Boolean IsAutoCheckForUpdates;
		Boolean IsCheckForPreviewUpdates;

		Boolean IsErrorWhileChecking;
		Boolean IsNoUpdate;
		Boolean IsAvailable { get; };
		Boolean IsDownloading { get; };
		Boolean IsErrorWhileDownloading { get; };
		Boolean IsInstalling { get; };
		Boolean IsDownloadingOrLater { get; };

		Boolean IsUpdateCardOpen;
		Boolean IsUpdateCardClosable { get; };
		Boolean IsCancelButtonVisible { get; };

		String UpdateCardTitle { get; };

		Boolean IsNoDownloadProgress { get; };
		Double DownloadProgress { get; };

		Windows.Foundation.Uri UpdateReleaseNotesLink { get; };

		void DownloadAndInstall();
		void Cancel();
		void Retry();
	}
}
