#include "BoolNegationConverter.idl"
#include "BoolToNegativeVisibilityConverter.idl"
#include "LoggerHelper.idl"
#include "TextBlockHelper.idl"
#include "PageFrame.idl"
#include "SettingsCard.idl"
#include "SettingsGroup.idl"
#include "KeyVisual.idl"
#include "ShortcutControl.idl"
#include "ShortcutDialog.idl"
#include "HomeViewModel.idl"
#include "EffectParametersViewModel.idl"
#include "ScalingModeEffectItem.idl"
#include "ScalingModeItem.idl"
#include "ScalingModesViewModel.idl"
#include "ScalingProfileViewModel.idl"
#include "SettingsViewModel.idl"
#include "CandidateWindowItem.idl"
#include "NewProfileViewModel.idl"
#include "AboutViewModel.idl"
#include "MainPage.idl"
#include "AboutPage.idl"
#include "HomePage.idl"
#include "ScalingConfigurationPage.idl"
#include "ProfilePage.idl"
#include "SettingsPage.idl"

namespace Magpie.App {
	enum HotkeyAction {
		Scale,
		Overlay,
		COUNT_OR_NONE
	};

	enum HotkeyError {
		NoError,
		Invalid,
		Occupied
	};

	struct StartUpOptions {
		Windows.Foundation.Rect MainWndRect;
		Boolean IsError;
		Boolean IsWndMaximized;
		Boolean IsNeedElevated;
	};

	runtimeclass App : Windows.UI.Xaml.Application, Windows.Foundation.IClosable {
		App();

		void SaveSettings();

		StartUpOptions Initialize(Int32 notUsed);

		Boolean IsShowTrayIcon { get; };
		event Windows.Foundation.EventHandler<Boolean> IsShowTrayIconChanged;

		UInt64 HwndMain;
		event Windows.Foundation.EventHandler<UInt64> HwndMainChanged;

		MainPage MainPage;

		void RestartAsElevated();
		void Quit();
	}
}
