namespace Magpie.App {
    runtimeclass CandidateWindowItem : Windows.UI.Xaml.Data.INotifyPropertyChanged {
        CandidateWindowItem(UInt64 hWnd, UInt32 dpi, Boolean isLightTheme, Windows.UI.Core.CoreDispatcher dispatcher);

        String Title { get; };
        Windows.UI.Xaml.Controls.IconElement Icon { get; };
        String DefaultProfileName { get; };

        String AUMID { get; };
        String Path { get; };
        String ClassName { get; };
    }
}
