namespace Magpie.App {
	enum CaptionButton {
		Minimize = 8,   // HTMINBUTTON
		Maximize = 9,   // HTMAXBUTTON
		Close = 20      // HTCLOSE
	};

	runtimeclass CaptionButtonsControl : Windows.UI.Xaml.Controls.StackPanel {
		CaptionButtonsControl();

		Windows.Foundation.Size CaptionButtonSize { get; };

		void HoverButton(CaptionButton button);
		void PressButton(CaptionButton button);
		void ReleaseButton(CaptionButton button);
		void ReleaseButtons();
		void LeaveButtons();

		void IsWindowMaximized(Boolean value);
		void IsWindowActive(Boolean value);
	}
}
