namespace Magpie.App {
	runtimeclass HomeViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		HomeViewModel();
		
		Boolean IsStopwatchOn{ get; };
		Single StopwatchProgressRingValue { get; };
		String StopwatchLabelText { get; };
		String StopwatchButtonText { get; };
		Boolean IsNotRunning { get; };
		UInt32 DownCount;

		void ToggleStopwatch();

		Boolean IsAutoRestore;
		Boolean IsWndToRestore { get; };
		String RestoreWndDesc { get; };

		void ActivateRestore();
		void ClearRestore();

		Boolean IsProcessElevated { get; };
		void RestartAsElevated();
		Boolean IsAlwaysRunAsElevated;

		Boolean ShowUpdateCard;
		Boolean IsAutoCheckForUpdates;
		void DownloadAndInstall();
		void ReleaseNotes();
		void RemindMeLater();
	}
}
