namespace Magpie.App
{
	[default_interface]
	runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
	{
		MainPage();

		void OnHostFocusChanged(Boolean isFocused);
		void Initialize(UInt64 hwndHost);

		UInt8 Theme;
	}
}
