namespace Magpie.App {
	runtimeclass ScalingType {
		ScalingType(String name, String desc);
		
		String Name { get; };
		String Desc { get; };
	}

	runtimeclass ScalingConfigurationPage : Windows.UI.Xaml.Controls.Page {
		ScalingConfigurationPage();

		ScalingConfigurationViewModel ViewModel { get; };

		static Windows.Globalization.NumberFormatting.INumberFormatter2 NumberFormatter { get; };

		// https://github.com/microsoft/microsoft-ui-xaml/issues/7579
		void UnloadObject(Windows.UI.Xaml.DependencyObject object);
	}
}
