namespace Magpie.App {
    runtimeclass ScalingModesViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
        ScalingModesViewModel();

        void Export();
        void Import();
        void ImportLegacy();

        Boolean ShowErrorMessage;

        IVector<IInspectable> DownscalingEffects { get; };
        Int32 DownscalingEffectIndex;
        Boolean DownscalingEffectHasParameters { get; };
        EffectParametersViewModel DownscalingEffectParameters { get; };
        
        Windows.UI.Xaml.Media.Animation.TransitionCollection ScalingModesListTransitions { get; };
        IObservableVector<IInspectable> ScalingModes { get; };

        void PrepareForAdd();
        String NewScalingModeName;
        IVector<IInspectable> NewScalingModeCopyFromList { get; };
        Int32 NewScalingModeCopyFrom;
        Boolean IsAddButtonEnabled { get; };
        void AddScalingMode();
    }
}
