namespace Magpie.App {
	runtimeclass ScalingType {
		ScalingType(String name, String desc);
		
		String Name { get; };
		String Desc { get; };
	}

	runtimeclass ScalingConfigurationPage : Windows.UI.Xaml.Controls.Page {
		ScalingConfigurationPage();

		ScalingModesViewModel ViewModel { get; };

		static IVector<IInspectable> ScalingTypes { get; };
		static Windows.Globalization.NumberFormatting.INumberFormatter2 NumberFormatter { get; };
	}
}
