namespace Magpie.App {
    runtimeclass ScalingConfigurationViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
        ScalingConfigurationViewModel();

        void Export();
        void Import();
        void ImportLegacy();

        Boolean ShowErrorMessage;
        
        Windows.UI.Xaml.Media.Animation.TransitionCollection ScalingModesListTransitions { get; };
        IObservableVector<IInspectable> ScalingModes { get; };

        void PrepareForAdd();
        String NewScalingModeName;
        IVector<IInspectable> NewScalingModeCopyFromList { get; };
        Int32 NewScalingModeCopyFrom;
        Boolean IsAddButtonEnabled { get; };
        void AddScalingMode();
    }
}
