namespace Magpie.App
{
	[default_interface]
	runtimeclass Settings 
	{
		Settings();

		static Boolean IsPortableMode();

		Boolean Initialize(String workingDir);
		Boolean Save();

		String WorkingDir{ get; };
	}
}
