namespace Magpie.App {
	runtimeclass SettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		SettingsViewModel();

		IVector<IInspectable> Languages { get; };
		Int32 Language;
		Int32 Theme;
		Boolean IsRunAtStartup;
		Boolean IsMinimizeAtStartup;
		Boolean IsMinimizeAtStartupEnabled { get; };
		Boolean IsPortableMode;
		void OpenConfigLocation();
		Boolean IsShowTrayIcon;

		Boolean IsProcessElevated { get; };
		Boolean IsAlwaysRunAsElevated;

		Boolean IsSimulateExclusiveFullscreen;
		Boolean IsInlineParams;
		Boolean IsDebugMode;
		Boolean IsDisableEffectCache;
		Boolean IsSaveEffectSources;
		Boolean IsWarningsAreErrors;
	}
}
