namespace Magpie.App
{
	[default_interface]
	runtimeclass Settings 
	{
		Settings();

		Boolean Initialize(UInt64 pLogger);

		Boolean Save();

		Boolean IsPortableMode;
		String WorkingDir{ get; };

		Int32 Theme;
		event Windows.Foundation.EventHandler<Int32> ThemeChanged;
	}
}
