namespace Magpie.App {
    [Windows.UI.Xaml.Markup.ContentProperty("Content")]
    runtimeclass SettingsExpander : Windows.UI.Xaml.Controls.Control {
        SettingsExpander();
        
        Object Header;
        Object Description;
        Windows.UI.Xaml.Controls.IconElement HeaderIcon;
        Object Content;

        static Windows.UI.Xaml.DependencyProperty HeaderProperty { get; };
        static Windows.UI.Xaml.DependencyProperty DescriptionProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty HeaderIconProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty ContentProperty{ get; };
    }
}
