namespace Magpie.App
{
	[default_interface]
	runtimeclass Settings 
	{
		Settings();

		static Boolean IsPortableMode();

		Boolean Initialize(String workingDir);
		Boolean Save();

		String WorkingDir{ get; };

		Int32 Theme;
		event Windows.Foundation.EventHandler<Int32> ThemeChanged;
	}
}
