namespace Magpie.App {
    runtimeclass SettingsExpanderItemStyleSelector : Windows.UI.Xaml.Controls.StyleSelector {
        SettingsExpanderItemStyleSelector();
        
        Windows.UI.Xaml.Style DefaultStyle;
        Windows.UI.Xaml.Style ClickableStyle;
    }

    [Windows.UI.Xaml.Markup.ContentProperty("Content")]
    runtimeclass SettingsExpander : Windows.UI.Xaml.Controls.Control {
        SettingsExpander();
        
        static Windows.UI.Xaml.DependencyProperty HeaderProperty { get; };
        static Windows.UI.Xaml.DependencyProperty DescriptionProperty { get; };
        static Windows.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
        static Windows.UI.Xaml.DependencyProperty ContentProperty { get; };
        static Windows.UI.Xaml.DependencyProperty ItemsHeaderProperty { get; };
        static Windows.UI.Xaml.DependencyProperty ItemsFooterProperty { get; };
        static Windows.UI.Xaml.DependencyProperty IsExpandedProperty { get; };
        static Windows.UI.Xaml.DependencyProperty ItemsProperty { get; };
        static Windows.UI.Xaml.DependencyProperty ItemsSourceProperty { get; };
        static Windows.UI.Xaml.DependencyProperty ItemTemplateProperty { get; };
        static Windows.UI.Xaml.DependencyProperty ItemContainerStyleSelectorProperty { get; };
        static Windows.UI.Xaml.DependencyProperty CanReorderItemsProperty { get; };

        Object Header;
        Object Description;
        Windows.UI.Xaml.Controls.IconElement HeaderIcon;
        Object Content;
        Windows.UI.Xaml.UIElement ItemsHeader;
        Windows.UI.Xaml.UIElement ItemsFooter;
        Boolean IsExpanded;
        IVector<Object> Items;
        Object ItemsSource;
        Object ItemTemplate;
        Windows.UI.Xaml.Controls.StyleSelector ItemContainerStyleSelector;
        Boolean CanReorderItems;

        event SignalDelegate Expanded;
        event SignalDelegate Collapsed;
    }
}
