namespace Magpie.App.Controls
{
	[Windows.UI.Xaml.TemplateVisualState("Normal", "CommonStates")]
	[Windows.UI.Xaml.TemplateVisualState("Disabled", "CommonStates")]
	runtimeclass Setting : Windows.UI.Xaml.Controls.ContentControl
	{
		Setting();

		void OnApplyTemplate();

		String MyHeader;
		Object Description;
		Object Icon;
		Object ActionContent;
	}
}
