namespace Magpie.App {
	runtimeclass SimpleStackPanel : Windows.UI.Xaml.Controls.Panel {
		SimpleStackPanel();

		static Windows.UI.Xaml.DependencyProperty OrientationProperty { get; };
		static Windows.UI.Xaml.DependencyProperty PaddingProperty { get; };
		static Windows.UI.Xaml.DependencyProperty SpacingProperty { get; };
		
		Windows.UI.Xaml.Controls.Orientation Orientation;
		Windows.UI.Xaml.Thickness Padding;
		Double Spacing;
	}
}
