namespace Magpie.App {
    runtimeclass ToastPage : Windows.UI.Xaml.Controls.Page {
        ToastPage(UInt64 hwndToast);

        void ShowMessageOnWindow(String message, UInt64 hwndTarget);
        
        // https://github.com/microsoft/microsoft-ui-xaml/issues/7579
        void UnloadObject(Windows.UI.Xaml.DependencyObject object);
    }
}
