name: code-analysis

on:
  push:
    paths: [ '.github/workflows/code-analysis.yml', 'Magpie.slnx', '*.props', 'scripts/publish.py', 'src/**' ]
  pull_request:
    paths: [ '.github/workflows/code-analysis.yml', 'Magpie.slnx', '*.props', 'scripts/publish.py', 'src/**' ]

jobs:
  code-analysis:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        tool: ["Microsoft C++ Code Analysis", "clang-tidy"]

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: '3.13'

    - name: Setup Conan
      run: pip install conan

    - name: Load Conan cache
      uses: actions/cache@v6
      with:
        path: ~/.conan2/p
        key: Conan-${{ hashFiles('src/**/conanfile.txt') }}-${{ case(matrix.tool == 'clang-tidy', 'ClangCL', 'MSVC') }}-x64

    - name: Run code analysis
      run: python scripts/code-analysis.py --tool="${{ matrix.tool }}"
